### ISSUE TITLE
Exception When Lacking Config.json

### ISSUE THREAD

**Issue by TTangNingzhi** [codegrits/CodeGRITS#3]
After the initial installation, when I open Configurations, if the json file does not exist, it will throw an exception.
```
java.lang.RuntimeException: java.io.FileNotFoundException: config.json (No such file or directory)
	at entity.Config.loadFromJson(Config.java:75)
	at component.ConfigDialog.<init>(ConfigDialog.java:95)
	at actions.ConfigAction.actionPerformed(ConfigAction.java:25)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:339)
    ...
Caused by: java.io.FileNotFoundException: config.json (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at entity.Config.loadFromJson(Config.java:60)
	... 62 more
```

**Comment by TTangNingzhi** [comment]
Checked for the existence of config.json each time before loading it.

**Comment by ranimkhojah** [comment]
How was this resolved? I have the same problem.
